# Generated by Django 4.2.26 on 2025-11-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('coach_country', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='PlayerDetailed',
            fields=[
                ('player_detailed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_physic', models.IntegerField(null=True)),
                ('player_country', models.CharField(max_length=2, null=True)),
                ('player_age', models.IntegerField(null=True)),
                ('player_foot', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='right', max_length=5)),
            ],
            options={
                'db_table': 'players_detailed',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=100, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('stadium_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
        migrations.CreateModel(
            name='PlayerTechnical',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50, null=True)),
                ('goal_scored', models.IntegerField(default=0)),
                ('assist_scored', models.IntegerField(default=0)),
                ('player_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
            ],
            options={
                'db_table': 'players_technical',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('win_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach')),
                ('win_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stadium')),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
    ]
